{% set version = "1.4.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rcmdcheck
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rcmdcheck_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rcmdcheck/rcmdcheck_{{ version }}.tar.gz
  sha256: bbd4ef7d514b8c2076196a7c4a6041d34623d55fbe73f2771758ce61fd32c9d0

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  # noarch builds on linux-64
  skip: True # [not linux-64]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base  {{ r_version }}
    - r-r6
    - r-callr >=3.1.1.9000
    - r-cli >=3.0.0
    - r-curl
    - r-desc >=1.2.0
    - r-digest
    - r-pkgbuild
    - r-prettyunits
    - r-rprojroot
    - r-sessioninfo >=1.1.1
    - r-withr
    - r-xopen
  run:
    - r-base  {{ r_version }}
    - r-r6
    - r-callr >=3.1.1.9000
    - r-cli >=3.0.0
    - r-curl
    - r-desc >=1.2.0
    - r-digest
    - r-pkgbuild
    - r-prettyunits
    - r-rprojroot
    - r-sessioninfo >=1.1.1
    - r-withr
    - r-xopen

test:
  commands:
    - $R -e "library('rcmdcheck')"           # [not win]
    - "\"%R%\" -e \"library('rcmdcheck')\""  # [win]

about:
  home: https://r-lib.github.io/rcmdcheck/, https://github.com/r-Lib/rcmdcheck#readme
  license: MIT
  summary: Run 'R CMD check' from 'R' and capture the results of the individual checks. Supports
    running checks in the background, timeouts, pretty printing and comparing check
    results.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
  skip-lints:
    # These are needed because of bug: https://github.com/anaconda-distribution/anaconda-linter/issues/197
    - http_url
    - invalid_url

    - host_section_needs_exact_pinnings
    - missing_dev_url
    - missing_description
    - missing_documentation

  anaconda-services:
    ref:  https://anaconda.zendesk.com/agent/tickets/35116
    reason: "needed for r-devtools"
    recipe-maintainers:
      - bkreider


# Package: rcmdcheck
# Title: Run 'R CMD check' from 'R' and Capture Results
# Version: 1.4.0
# Authors@R: person(given = "Gabor", family = "Csardi", role = c("cre", "aut"), email = "csardi.gabor@gmail.com")
# Description: Run 'R CMD check' from 'R' and capture the results of the individual checks. Supports running checks in the background, timeouts, pretty printing and comparing check results.
# License: MIT + file LICENSE
# URL: https://r-lib.github.io/rcmdcheck/, https://github.com/r-Lib/rcmdcheck#readme
# BugReports: https://github.com/r-Lib/rcmdcheck/issues
# Imports: callr (>= 3.1.1.9000), cli (>= 3.0.0), curl, desc (>= 1.2.0), digest, pkgbuild, prettyunits, R6, rprojroot, sessioninfo (>= 1.1.1), utils, withr, xopen
# Suggests: covr, knitr, mockery, processx, ps, rmarkdown, svglite, testthat, webfakes
# Encoding: UTF-8
# RoxygenNote: 7.1.2
# Config/testthat/edition: 3
# NeedsCompilation: no
# Packaged: 2021-09-23 11:13:42 UTC; gaborcsardi
# Author: Gabor Csardi [cre, aut]
# Maintainer: Gabor Csardi <csardi.gabor@gmail.com>
# Repository: CRAN
# Date/Publication: 2021-09-27 15:10:02 UTC
