{% set version = '1.3.3' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rcmdcheck
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rcmdcheck_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rcmdcheck/rcmdcheck_{{ version }}.tar.gz
  sha256: 1ab679eb1976d74cd3be5bcad0af7fcc673dbdfd4406bbce32591c8fddfb93b4

build:
  merge_build_host: True  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-r6
    - r-callr >=3.1.1.9000
    - r-cli >=1.1.0
    - r-crayon
    - r-desc >=1.2.0
    - r-digest
    - r-pkgbuild
    - r-prettyunits
    - r-rprojroot
    - r-sessioninfo >=1.1.1
    - r-withr
    - r-xopen
  run:
    - r-base
    - r-r6
    - r-callr >=3.1.1.9000
    - r-cli >=1.1.0
    - r-crayon
    - r-desc >=1.2.0
    - r-digest
    - r-pkgbuild
    - r-prettyunits
    - r-rprojroot
    - r-sessioninfo >=1.1.1
    - r-withr
    - r-xopen

test:
  commands:
    - $R -e "library('rcmdcheck')"           # [not win]
    - "\"%R%\" -e \"library('rcmdcheck')\""  # [win]

about:
  home: https://github.com/r-Lib/rcmdcheck#readme
  license: MIT
  summary: Run 'R CMD check' from 'R' and capture the results of the individual checks. Supports
    running checks in the background, timeouts, pretty printing and comparing check
    results.
  license_family: MIT

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: rcmdcheck
# Title: Run 'R CMD check' from 'R' and Capture Results
# Version: 1.3.3
# Author: Gabor Csardi
# Maintainer: Gabor Csardi <csardi.gabor@gmail.com>
# Description: Run 'R CMD check' from 'R' and capture the results of the individual checks. Supports running checks in the background, timeouts, pretty printing and comparing check results.
# License: MIT + file LICENSE
# LazyData: true
# URL: https://github.com/r-Lib/rcmdcheck#readme
# BugReports: https://github.com/r-Lib/rcmdcheck/issues
# RoxygenNote: 6.1.1
# Suggests: covr, knitr, mockery, rmarkdown, testthat
# Imports: callr (>= 3.1.1.9000), cli (>= 1.1.0), crayon, desc (>= 1.2.0), digest, pkgbuild, prettyunits, R6, rprojroot, sessioninfo (>= 1.1.1), utils, withr, xopen
# Encoding: UTF-8
# NeedsCompilation: no
# Packaged: 2019-05-07 11:39:19 UTC; gaborcsardi
# Repository: CRAN
# Date/Publication: 2019-05-07 12:00:02 UTC
