travis:
  secure:
    BINSTAR_TOKEN: HLO1UIYyQS5RUHry6N8Vf8RTxkxa4/XazobRTVU6PLly+BEXBwlCuXP4ILe8uXU8xpvtk2M2yH9GnQLMJ2d+BeP4CJ14+XKnYe4zLSiml075Y3JLYpmRrrnT2dTab9F6fH8Wk1xHfSIK/SFxvnqP8e0jZev63EUbomSo0F5iYUqse3u8834hfyfC23JKoomTfB9QyOgGYZkb23keViiuOz6jYsVJPHo5r0wEhyOmDXNF52VfX4g/1r+CwBiJpC1SO5uKdGHdzobS9cWIKD4e/1uPtjjP/jcqwIuxdmGnuK+WDcEy9oFCpOdzQx/YBwwM3zbKeytdzqIP/i1GXmC0yhMMT5jm4iJpakqbLJNmOH+pejsF4msvaT/6c37uV9CUuAPfmgMz7RoMbZMQJZxEc0648dUaSxtxqKyTAA3NyKTK0AA0L5Pmfo9y0Kk+QJnFSZQ9YUBxvmUwi0hqSrxPTipFbH3oL6TqGVIMdpNzX3o+0P6T1hXIUlgfowRT4KZWyrrj9cd0KW4b7bpZ3b+BlJxurWeXCxDmIRAjHZvwvxRtFLTbExcVciqUSL8AsSVk+xKHW8Owh4wm6icgtcnLNyUvxSO+MEjNZCpQWQjEzIT6ZyJ3/6LpCvCS+ba4xLWOc1sMHCr91I6tlZqV9d2R3i5nE6B5w2ORFrOJ8sScvrE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
